on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@latest

    - name: 'Build'
      shell: bash
      run: |
        echo "::group::Build"
        npm install
        npm run build
        echo "::endgroup::"

    - name: 'upload'
      uses: actions/upload-pages-artifact@latest
      with: 
        path: build

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@latest
      with:
        token: ${{ github.token }}
